apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3  # Scalato: servizio stateless, critico per autenticazione concorrente
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: cpiac_auth:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URI
              value: "postgresql://admin:password@postgres-service:5432/auth_db"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
