apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-auth
spec:
  stripPrefix:
    prefixes:
      - /api/auth

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-inventory
spec:
  stripPrefix:
    prefixes:
      - /api/inventory

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-orders
spec:
  stripPrefix:
    prefixes:
      - /api/orders

---
# ----------------------------------------------------------------
# Frontend (Nessun rewrite necessario, ascolta sulla root)
# ----------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 8080

---
# ----------------------------------------------------------------
# Auth Service
# ----------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-api-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5001

---
# ----------------------------------------------------------------
# Inventory Service
# ----------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-api-inventory@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /api/inventory
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 5002

---
# ----------------------------------------------------------------
# Order Service
# ----------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-api-orders@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 5003
