apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 3  # Scalato: servizio stateless, critico per gestione giacenze concorrente
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: cpiac_inventory:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URI
              value: "postgresql://admin:password@postgres-service:5432/inventory_db"
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"
