apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3  # Scalato: servizio stateless, critico per elaborazione ordini concorrente
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: cpiac_order:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: DATABASE_URI
              value: "postgresql://admin:password@postgres-service:5432/order_db"
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"
